name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Install dependencies
      run: |
        cd lambdas
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        cd lambdas
        pytest

  validate:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.10

    - name: Install dependencies for infra
      run: |
        cd Infra
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install dependencies for layers
      run: |
        cd lambdas
        python -m pip install --upgrade pip
        mkdir -p python
        pip install -r requirements.txt -t python

    - name: create Zip the layer
      run: |
        cd lambdas
        zip -r python.zip python

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Validate IAC with CDK
      run: |
        ls -la
        cd Infra
        cdk synthesize
